// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Package pages hosts the page-level templ components — each one slots into

// the layout.Layout chrome via Renderer.RenderTempl. Pages take their own

// typed props directly (no opaque `Body any` bag); the home page has no

// per-request data, so Home() takes no arguments.

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Home is the empty-state landing page rendered when no projects are mounted.
// Populated-state requests are 303-redirected to the first project's overview
// before this ever runs — see web.handleHome.
//
// 1:1 port of templates/pages/home.tmpl: same copy, same class names, same
// hrefs. Layout / styling stay identical until Phase 2 explicitly relaxes
// "behaviour-identical, layout-identical."
func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"empty-state\"><h1>Welcome to tickets_please</h1><p class=\"subtitle\">No projects are mounted on this server yet. Mount one to get started — humans and LLM agents will share the same audit trail.</p><div class=\"page-actions\"><a class=\"btn btn-primary\" href=\"/p/new\">Create a new project</a> <a class=\"btn\" href=\"/p/load\">Load an existing project</a></div><p class=\"footnote\">Or run <code>tickets_please mcp</code> from a repo containing a <code>.tickets_please/project.yaml</code> to bind a session and have the project appear in the sidebar.</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
