// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "tickets_please/internal/web/components/partials"

// Logs renders the /logs page: a header + the htmx-polling <pre> wrapper that
// auto-tails the in-process log ring every 2 seconds. The inner content of
// #logs-tail comes from the LogsPre partial so the full page render and the
// HX-Request fragment swap share a single source of truth.
//
// 1:1 port of templates/pages/logs.tmpl — same headings, same wrapper id, same
// htmx attributes (hx-get, hx-trigger, hx-swap, hx-on::before-request,
// hx-on::after-swap), same inline scroll-to-bottom script.
func Logs(p partials.LogsPreProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"logs-page\"><header class=\"page-header\"><h1>Server logs</h1><p class=\"subtitle\">Structured log records, JSON-encoded, oldest first. Mirrors what the operator sees on stderr.</p><p class=\"muted\">Auto-tailing every 2 seconds (htmx in-place swap; auto-scrolls only when you're at the bottom).</p></header><div id=\"logs-tail\" hx-get=\"/logs\" hx-trigger=\"every 2s\" hx-swap=\"innerHTML\" hx-on::before-request=\"(function(el){var p=el.querySelector('pre');if(!p){el.dataset.atBottom='1';el.dataset.scrollTop='0';return;}el.dataset.atBottom=(Math.abs(p.scrollHeight-p.clientHeight-p.scrollTop)<8)?'1':'0';el.dataset.scrollTop=String(p.scrollTop);})(this)\" hx-on::after-swap=\"(function(el){var p=el.querySelector('pre');if(!p)return;if(el.dataset.atBottom==='1'){p.scrollTop=p.scrollHeight;}else{p.scrollTop=parseInt(el.dataset.scrollTop||'0',10);}})(this)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.LogsPre(p).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><script>\n\t\t\t// Initial scroll-to-bottom on first page load.\n\t\t\t(function(){var p=document.querySelector('#logs-tail pre');if(p)p.scrollTop=p.scrollHeight;})();\n\t\t</script></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
